name: Frontend CI

on: [push, pull_request]

jobs:
  BUILD_GENERATE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run build --if-present
      - run: npm run generate

      - name: Artifact [frontend]
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: frontend/dist
